// svelte-ui/src/routes/cli-auth/+page.svelte
<script lang="ts">
  import { Terminal, Check, X, AlertCircle } from "lucide-svelte";
  import { api } from "$lib/api/client";
  import { authClient } from "$lib/auth-client";
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";

  let code = $derived($page.url.searchParams.get("code") ?? "");
  let loading = $state(false);
  let error = $state<string | null>(null);
  let approved = $state(false);
  let denied = $state(false);

  const session = authClient.useSession();

  $effect(() => {
    if (!$session.data) {
      goto(`/auth?redirect=${encodeURIComponent(`/cli-auth?code=${code}`)}`);
    }
  });

  async function handleApprove() {
    if (!code) {
      error = "No auth code provided";
      return;
    }
    loading = true;
    error = null;

    try {
      await api.api["cli-auth"].post({ code, action: "approve" });
      approved = true;
    } catch (err) {
      error = err instanceof Error ? err.message : "Failed to approve CLI session";
    } finally {
      loading = false;
    }
  }

  async function handleDeny() {
    if (!code) return;
    loading = true;
    error = null;

    try {
      await api.api["cli-auth"].post({ code, action: "deny" });
      denied = true;
    } catch (err) {
      error = err instanceof Error ? err.message : "Failed to deny CLI session";
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex h-full items-center justify-center">
  <div class="flex flex-col items-center gap-6 w-full max-w-sm px-4">
    <div class="flex flex-col items-center gap-2">
      <Terminal class="size-10 text-foreground" />
      <h1 class="text-xl font-semibold">CLI Authentication</h1>
      <p class="text-sm text-muted-foreground text-center">
        A CLI session is requesting access to your account.
      </p>
    </div>

    {#if !code}
      <div class="w-full rounded-lg border border-destructive/50 bg-destructive/10 p-4 text-center">
        <p class="text-sm text-destructive">No authentication code provided.</p>
        <p class="text-xs text-muted-foreground mt-1">Please use the link from your CLI.</p>
      </div>
    {:else if approved}
      <div class="w-full rounded-lg border border-green-500/50 bg-green-500/10 p-4 text-center space-y-2">
        <Check class="size-8 text-green-500 mx-auto" />
        <p class="text-sm font-medium text-green-500">CLI session approved!</p>
        <p class="text-xs text-muted-foreground">You can return to your terminal. This window can be closed.</p>
      </div>
    {:else if denied}
      <div class="w-full rounded-lg border border-muted bg-muted/50 p-4 text-center space-y-2">
        <X class="size-8 text-muted-foreground mx-auto" />
        <p class="text-sm font-medium text-foreground">CLI session denied.</p>
        <p class="text-xs text-muted-foreground">The CLI will need to authenticate again.</p>
      </div>
    {:else}
      <!-- Auth code display -->
      <div class="w-full rounded-lg border border-border bg-card p-4 text-center">
        <p class="text-xs text-muted-foreground uppercase tracking-wider mb-1">Auth Code</p>
        <p class="text-lg font-mono font-semibold text-foreground tracking-widest">{code}</p>
      </div>

      <p class="text-xs text-muted-foreground text-center">
        Verify this code matches what your CLI is showing before approving.
      </p>

      {#if error}
        <div class="w-full flex items-start gap-2 rounded-lg border border-destructive/50 bg-destructive/10 p-3">
          <AlertCircle class="size-4 text-destructive shrink-0 mt-0.5" />
          <p class="text-sm text-destructive">{error}</p>
        </div>
      {/if}

      <div class="w-full flex gap-3">
        <button
          onclick={handleApprove}
          disabled={loading}
          class="inline-flex h-9 flex-1 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow hover:bg-primary/90 transition-colors disabled:opacity-50"
        >
          {loading ? "Processing..." : "Approve"}
        </button>
        <button
          onclick={handleDeny}
          disabled={loading}
          class="inline-flex h-9 flex-1 items-center justify-center rounded-md border border-border px-4 text-sm font-medium text-foreground shadow-sm hover:bg-muted transition-colors disabled:opacity-50"
        >
          Deny
        </button>
      </div>
    {/if}
  </div>
</div>

// _legacy/ui/src/pages/CliAuth.tsx
import { useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams, useSearchParams } from "@/lib/router";
import { Button } from "@/components/ui/button";
import { accessApi } from "../api/access";
import { authApi } from "../api/auth";
import { queryKeys } from "../lib/queryKeys";

export function CliAuthPage() {
  const queryClient = useQueryClient();
  const params = useParams();
  const [searchParams] = useSearchParams();
  const challengeId = (params.id ?? "").trim();
  const token = (searchParams.get("token") ?? "").trim();
  const currentPath = useMemo(
    () => `/cli-auth/${encodeURIComponent(challengeId)}${token ? `?token=${encodeURIComponent(token)}` : ""}`,
    [challengeId, token],
  );

  const sessionQuery = useQuery({
    queryKey: queryKeys.auth.session,
    queryFn: () => authApi.getSession(),
    retry: false,
  });
  const challengeQuery = useQuery({
    queryKey: ["cli-auth-challenge", challengeId, token],
    queryFn: () => accessApi.getCliAuthChallenge(challengeId, token),
    enabled: challengeId.length > 0 && token.length > 0,
    retry: false,
  });

  const approveMutation = useMutation({
    mutationFn: () => accessApi.approveCliAuthChallenge(challengeId, token),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: queryKeys.auth.session });
      await challengeQuery.refetch();
    },
  });

  const cancelMutation = useMutation({
    mutationFn: () => accessApi.cancelCliAuthChallenge(challengeId, token),
    onSuccess: async () => {
      await challengeQuery.refetch();
    },
  });

  if (!challengeId || !token) {
    return <div className="mx-auto max-w-xl py-10 text-sm text-destructive">Invalid CLI auth URL.</div>;
  }

  if (sessionQuery.isLoading || challengeQuery.isLoading) {
    return <div className="mx-auto max-w-xl py-10 text-sm text-muted-foreground">Loading CLI auth challenge...</div>;
  }

  if (challengeQuery.error) {
    return (
      <div className="mx-auto max-w-xl py-10">
        <div className="rounded-lg border border-border bg-card p-6">
          <h1 className="text-lg font-semibold">CLI auth challenge unavailable</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            {challengeQuery.error instanceof Error ? challengeQuery.error.message : "Challenge is invalid or expired."}
          </p>
        </div>
      </div>
    );
  }

  const challenge = challengeQuery.data;
  if (!challenge) {
    return <div className="mx-auto max-w-xl py-10 text-sm text-destructive">CLI auth challenge unavailable.</div>;
  }

  if (challenge.status === "approved") {
    return (
      <div className="mx-auto max-w-xl py-10">
        <div className="rounded-lg border border-border bg-card p-6">
          <h1 className="text-xl font-semibold">CLI access approved</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            The ClawDev CLI can now finish authentication on the requesting machine.
          </p>
          <p className="mt-4 text-sm text-muted-foreground">
            Command: <span className="font-mono text-foreground">{challenge.command}</span>
          </p>
        </div>
      </div>
    );
  }

  if (challenge.status === "cancelled" || challenge.status === "expired") {
    return (
      <div className="mx-auto max-w-xl py-10">
        <div className="rounded-lg border border-border bg-card p-6">
          <h1 className="text-xl font-semibold">
            {challenge.status === "expired" ? "CLI auth challenge expired" : "CLI auth challenge cancelled"}
          </h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Start the CLI auth flow again from your terminal to generate a new approval request.
          </p>
        </div>
      </div>
    );
  }

  if (challenge.requiresSignIn || !sessionQuery.data) {
    return (
      <div className="mx-auto max-w-xl py-10">
        <div className="rounded-lg border border-border bg-card p-6">
          <h1 className="text-xl font-semibold">Sign in required</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Sign in or create an account, then return to this page to approve the CLI access request.
          </p>
          <Button asChild className="mt-4">
            <Link to={`/auth?next=${encodeURIComponent(currentPath)}`}>Sign in / Create account</Link>
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-xl py-10">
      <div className="rounded-lg border border-border bg-card p-6">
        <h1 className="text-xl font-semibold">Approve ClawDev CLI access</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          A local ClawDev CLI process is requesting board access to this instance.
        </p>

        <div className="mt-5 space-y-3 text-sm">
          <div>
            <div className="text-muted-foreground">Command</div>
            <div className="font-mono text-foreground">{challenge.command}</div>
          </div>
          <div>
            <div className="text-muted-foreground">Client</div>
            <div className="text-foreground">{challenge.clientName ?? "clawdev cli"}</div>
          </div>
          <div>
            <div className="text-muted-foreground">Requested access</div>
            <div className="text-foreground">
              {challenge.requestedAccess === "instance_admin_required" ? "Instance admin" : "Board"}
            </div>
          </div>
          {challenge.requestedCompanyName && (
            <div>
              <div className="text-muted-foreground">Requested company</div>
              <div className="text-foreground">{challenge.requestedCompanyName}</div>
            </div>
          )}
        </div>

        {(approveMutation.error || cancelMutation.error) && (
          <p className="mt-4 text-sm text-destructive">
            {(approveMutation.error ?? cancelMutation.error) instanceof Error
              ? ((approveMutation.error ?? cancelMutation.error) as Error).message
              : "Failed to update CLI auth challenge"}
          </p>
        )}

        {!challenge.canApprove && (
          <p className="mt-4 text-sm text-destructive">
            This challenge requires instance-admin access. Sign in with an instance admin account to approve it.
          </p>
        )}

        <div className="mt-5 flex gap-3">
          <Button
            onClick={() => approveMutation.mutate()}
            disabled={!challenge.canApprove || approveMutation.isPending || cancelMutation.isPending}
          >
            {approveMutation.isPending ? "Approving..." : "Approve CLI access"}
          </Button>
          <Button
            type="button"
            variant="outline"
            onClick={() => cancelMutation.mutate()}
            disabled={approveMutation.isPending || cancelMutation.isPending}
          >
            {cancelMutation.isPending ? "Cancelling..." : "Cancel"}
          </Button>
        </div>
      </div>
    </div>
  );
}
