// packages/plugins/examples/plugin-hello-world-example/src/ui/index.svelte
<!--
  HelloWorldDashboardWidget — minimal plugin UI contribution.
  Svelte 5 port of the React version.
-->
<script lang="ts">
  import type { PluginWidgetProps } from "@clawdev/plugin-sdk/ui-svelte";

  let { context }: PluginWidgetProps = $props();
</script>

<section aria-label="Hello world plugin widget">
  <strong>Hello world</strong>
  <div>This widget was added by @clawdev/plugin-hello-world-example.</div>
  <div>Company context: {context.companyId}</div>
</section>

// packages/plugins/examples/plugin-hello-world-example/src/ui/index.tsx
import type { PluginWidgetProps } from "@clawdev/plugin-sdk/ui";

const WIDGET_LABEL = "Hello world plugin widget";

/**
 * Example dashboard widget showing the smallest possible UI contribution.
 */
export function HelloWorldDashboardWidget({ context }: PluginWidgetProps) {
  return (
    <section aria-label={WIDGET_LABEL}>
      <strong>Hello world</strong>
      <div>This widget was added by @clawdev/plugin-hello-world-example.</div>
      {/* Include host context so authors can see where scoped IDs come from. */}
      <div>Company context: {context.companyId}</div>
    </section>
  );
}
