// packages/plugins/examples/plugin-authoring-smoke-example/src/ui/index.tsx
import { usePluginAction, usePluginData, type PluginWidgetProps } from "@clawdev/plugin-sdk/ui";

type HealthData = {
  status: "ok" | "degraded" | "error";
  checkedAt: string;
};

export function DashboardWidget(_props: PluginWidgetProps) {
  const { data, loading, error } = usePluginData<HealthData>("health");
  const ping = usePluginAction("ping");

  if (loading) return <div>Loading plugin health...</div>;
  if (error) return <div>Plugin error: {error.message}</div>;

  return (
    <div style={{ display: "grid", gap: "0.5rem" }}>
      <strong>Plugin Authoring Smoke Example</strong>
      <div>Health: {data?.status ?? "unknown"}</div>
      <div>Checked: {data?.checkedAt ?? "never"}</div>
      <button onClick={() => void ping()}>Ping Worker</button>
    </div>
  );
}

// packages/plugins/examples/plugin-authoring-smoke-example/src/ui/index.svelte
<!--
  DashboardWidget — smoke test plugin demonstrating data + actions.
  Svelte 5 port of the React version.
-->
<script lang="ts">
  import { pluginData, pluginAction } from "@clawdev/plugin-sdk/ui-svelte";
  import type { PluginWidgetProps } from "@clawdev/plugin-sdk/ui-svelte";

  type HealthData = {
    status: "ok" | "degraded" | "error";
    checkedAt: string;
  };

  let { context }: PluginWidgetProps = $props();

  const health = pluginData<HealthData>("health");
  const ping = pluginAction("ping");
</script>

{#if $health.loading}
  <div>Loading plugin health...</div>
{:else if $health.error}
  <div>Plugin error: {$health.error.message}</div>
{:else}
  <div style="display: grid; gap: 0.5rem;">
    <strong>Plugin Authoring Smoke Example</strong>
    <div>Health: {$health.data?.status ?? "unknown"}</div>
    <div>Checked: {$health.data?.checkedAt ?? "never"}</div>
    <button onclick={() => void ping()}>Ping Worker</button>
  </div>
{/if}
