// ui/src/pages/Agents.tsx
import { useState, useEffect, useMemo } from "react";
import { Link, useNavigate, useLocation } from "@/lib/router";
import { useQuery } from "@tanstack/react-query";
import { agentsApi, type OrgNode } from "../api/agents";
import { heartbeatsApi } from "../api/heartbeats";
import { useCompany } from "../context/CompanyContext";
import { useDialog } from "../context/DialogContext";
import { useBreadcrumbs } from "../context/BreadcrumbContext";
import { useSidebar } from "../context/SidebarContext";
import { queryKeys } from "../lib/queryKeys";
import { StatusBadge } from "../components/StatusBadge";
import { agentStatusDot, agentStatusDotDefault } from "../lib/status-colors";
import { EntityRow } from "../components/EntityRow";
import { EmptyState } from "../components/EmptyState";
import { PageSkeleton } from "../components/PageSkeleton";
import { relativeTime, cn, agentRouteRef, agentUrl } from "../lib/utils";
import { PageTabBar } from "../components/PageTabBar";
import { Tabs } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Bot, Plus, List, GitBranch, SlidersHorizontal } from "lucide-react";
import { AGENT_ROLE_LABELS, type Agent } from "@clawdev/shared";

const adapterLabels: Record<string, string> = {
  claude_local: "Claude",
  codex_local: "Codex",
  gemini_local: "Gemini",
  opencode_local: "OpenCode",
  cursor: "Cursor",
  openclaw_gateway: "OpenClaw Gateway",
  process: "Process",
  http: "HTTP",
};

const roleLabels = AGENT_ROLE_LABELS as Record<string, string>;

type FilterTab = "all" | "active" | "paused" | "error";

function matchesFilter(status: string, tab: FilterTab, showTerminated: boolean): boolean {
  if (status === "terminated") return showTerminated;
  if (tab === "all") return true;
  if (tab === "active") return status === "active" || status === "running" || status === "idle";
  if (tab === "paused") return status === "paused";
  if (tab === "error") return status === "error";
  return true;
}

function filterAgents(agents: Agent[], tab: FilterTab, showTerminated: boolean): Agent[] {
  return agents
    .filter((a) => matchesFilter(a.status, tab, showTerminated))
    .sort((a, b) => a.name.localeCompare(b.name));
}

function filterOrgTree(nodes: OrgNode[], tab: FilterTab, showTerminated: boolean): OrgNode[] {
  return nodes
    .reduce<OrgNode[]>((acc, node) => {
      const filteredReports = filterOrgTree(node.reports, tab, showTerminated);
      if (matchesFilter(node.status, tab, showTerminated) || filteredReports.length > 0) {
        acc.push({ ...node, reports: filteredReports });
      }
      return acc;
    }, [])
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function Agents() {
  const { selectedCompanyId } = useCompany();
  const { openNewAgent } = useDialog();
  const { setBreadcrumbs } = useBreadcrumbs();
  const navigate = useNavigate();
  const location = useLocation();
  const { isMobile } = useSidebar();
  const pathSegment = location.pathname.split("/").pop() ?? "all";
  const tab: FilterTab = (pathSegment === "all" || pathSegment === "active" || pathSegment === "paused" || pathSegment === "error") ? pathSegment : "all";
  const [view, setView] = useState<"list" | "org">("org");
  const forceListView = isMobile;
  const effectiveView: "list" | "org" = forceListView ? "list" : view;
  const [showTerminated, setShowTerminated] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);

  const { data: agents, isLoading, error } = useQuery({
    queryKey: queryKeys.agents.list(selectedCompanyId!),
    queryFn: () => agentsApi.list(selectedCompanyId!),
    enabled: !!selectedCompanyId,
  });

  const { data: orgTree } = useQuery({
    queryKey: queryKeys.org(selectedCompanyId!),
    queryFn: () => agentsApi.org(selectedCompanyId!),
    enabled: !!selectedCompanyId && effectiveView === "org",
  });

  const { data: runs } = useQuery({
    queryKey: queryKeys.heartbeats(selectedCompanyId!),
    queryFn: () => heartbeatsApi.list(selectedCompanyId!),
    enabled: !!selectedCompanyId,
    refetchInterval: 15_000,
  });

  // Map agentId -> first live run + live run count
  const liveRunByAgent = useMemo(() => {
    const map = new Map<string, { runId: string; liveCount: number }>();
    for (const r of runs ?? []) {
      if (r.status !== "running" && r.status !== "queued") continue;
      const existing = map.get(r.agentId);
      if (existing) {
        existing.liveCount += 1;
        continue;
      }
      map.set(r.agentId, { runId: r.id, liveCount: 1 });
    }
    return map;
  }, [runs]);

  const agentMap = useMemo(() => {
    const map = new Map<string, Agent>();
    for (const a of agents ?? []) map.set(a.id, a);
    return map;
  }, [agents]);

  useEffect(() => {
    setBreadcrumbs([{ label: "Agents" }]);
  }, [setBreadcrumbs]);

  if (!selectedCompanyId) {
    return <EmptyState icon={Bot} message="Select a company to view agents." />;
  }

  if (isLoading) {
    return <PageSkeleton variant="list" />;
  }

  const filtered = filterAgents(agents ?? [], tab, showTerminated);
  const filteredOrg = filterOrgTree(orgTree ?? [], tab, showTerminated);

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <Tabs value={tab} onValueChange={(v) => navigate(`/agents/${v}`)}>
          <PageTabBar
            items={[
              { value: "all", label: "All" },
              { value: "active", label: "Active" },
              { value: "paused", label: "Paused" },
              { value: "error", label: "Error" },
            ]}
            value={tab}
            onValueChange={(v) => navigate(`/agents/${v}`)}
          />
        </Tabs>
        <div className="flex items-center gap-2">
          {/* Filters */}
          <div className="relative">
            <button
              className={cn(
                "flex items-center gap-1.5 px-2 py-1.5 text-xs transition-colors border border-border",
                filtersOpen || showTerminated ? "text-foreground bg-accent" : "text-muted-foreground hover:bg-accent/50"
              )}
              onClick={() => setFiltersOpen(!filtersOpen)}
            >
              <SlidersHorizontal className="h-3 w-3" />
              Filters
              {showTerminated && <span className="ml-0.5 px-1 bg-foreground/10 rounded text-[10px]">1</span>}
            </button>
            {filtersOpen && (
              <div className="absolute right-0 top-full mt-1 z-50 w-48 border border-border bg-popover shadow-md p-1">
                <button
                  className="flex items-center gap-2 w-full px-2 py-1.5 text-xs text-left hover:bg-accent/50 transition-colors"
                  onClick={() => setShowTerminated(!showTerminated)}
                >
                  <span className={cn(
                    "flex items-center justify-center h-3.5 w-3.5 border border-border rounded-sm",
                    showTerminated && "bg-foreground"
                  )}>
                    {showTerminated && <span className="text-background text-[10px] leading-none">&#10003;</span>}
                  </span>
                  Show terminated
                </button>
              </div>
            )}
          </div>
          {/* View toggle */}
          {!forceListView && (
            <div className="flex items-center border border-border">
              <button
                className={cn(
                  "p-1.5 transition-colors",
                  effectiveView === "list" ? "bg-accent text-foreground" : "text-muted-foreground hover:bg-accent/50"
                )}
                onClick={() => setView("list")}
              >
                <List className="h-3.5 w-3.5" />
              </button>
              <button
                className={cn(
                  "p-1.5 transition-colors",
                  effectiveView === "org" ? "bg-accent text-foreground" : "text-muted-foreground hover:bg-accent/50"
                )}
                onClick={() => setView("org")}
              >
                <GitBranch className="h-3.5 w-3.5" />
              </button>
            </div>
          )}
          <Button size="sm" variant="outline" onClick={openNewAgent}>
            <Plus className="h-3.5 w-3.5 mr-1.5" />
            New Agent
          </Button>
        </div>
      </div>

      {filtered.length > 0 && (
        <p className="text-xs text-muted-foreground">{filtered.length} agent{filtered.length !== 1 ? "s" : ""}</p>
      )}

      {error && <p className="text-sm text-destructive">{error.message}</p>}

      {agents && agents.length === 0 && (
        <EmptyState
          icon={Bot}
          message="Create your first agent to get started."
          action="New Agent"
          onAction={openNewAgent}
        />
      )}

      {/* List view */}
      {effectiveView === "list" && filtered.length > 0 && (
        <div className="border border-border">
          {filtered.map((agent) => {
            return (
              <EntityRow
                key={agent.id}
                title={agent.name}
                subtitle={`${roleLabels[agent.role] ?? agent.role}${agent.title ? ` - ${agent.title}` : ""}`}
                to={agentUrl(agent)}
                leading={
                  <span className="relative flex h-2.5 w-2.5">
                    <span
                      className={`absolute inline-flex h-full w-full rounded-full ${agentStatusDot[agent.status] ?? agentStatusDotDefault}`}
                    />
                  </span>
                }
                trailing={
                  <div className="flex items-center gap-3">
                    <span className="sm:hidden">
                      {liveRunByAgent.has(agent.id) ? (
                        <LiveRunIndicator
                          agentRef={agentRouteRef(agent)}
                          runId={liveRunByAgent.get(agent.id)!.runId}
                          liveCount={liveRunByAgent.get(agent.id)!.liveCount}
                        />
                      ) : (
                        <StatusBadge status={agent.status} />
                      )}
                    </span>
                    <div className="hidden sm:flex items-center gap-3">
                      {liveRunByAgent.has(agent.id) && (
                        <LiveRunIndicator
                          agentRef={agentRouteRef(agent)}
                          runId={liveRunByAgent.get(agent.id)!.runId}
                          liveCount={liveRunByAgent.get(agent.id)!.liveCount}
                        />
                      )}
                      <span className="text-xs text-muted-foreground font-mono w-14 text-right">
                        {adapterLabels[agent.adapterType] ?? agent.adapterType}
                      </span>
                      <span className="text-xs text-muted-foreground w-16 text-right">
                        {agent.lastHeartbeatAt ? relativeTime(agent.lastHeartbeatAt) : "—"}
                      </span>
                      <span className="w-20 flex justify-end">
                        <StatusBadge status={agent.status} />
                      </span>
                    </div>
                  </div>
                }
              />
            );
          })}
        </div>
      )}

      {effectiveView === "list" && agents && agents.length > 0 && filtered.length === 0 && (
        <p className="text-sm text-muted-foreground text-center py-8">
          No agents match the selected filter.
        </p>
      )}

      {/* Org chart view */}
      {effectiveView === "org" && filteredOrg.length > 0 && (
        <div className="border border-border py-1">
          {filteredOrg.map((node) => (
            <OrgTreeNode key={node.id} node={node} depth={0} agentMap={agentMap} liveRunByAgent={liveRunByAgent} />
          ))}
        </div>
      )}

      {effectiveView === "org" && orgTree && orgTree.length > 0 && filteredOrg.length === 0 && (
        <p className="text-sm text-muted-foreground text-center py-8">
          No agents match the selected filter.
        </p>
      )}

      {effectiveView === "org" && orgTree && orgTree.length === 0 && (
        <p className="text-sm text-muted-foreground text-center py-8">
          No organizational hierarchy defined.
        </p>
      )}
    </div>
  );
}

function OrgTreeNode({
  node,
  depth,
  agentMap,
  liveRunByAgent,
}: {
  node: OrgNode;
  depth: number;
  agentMap: Map<string, Agent>;
  liveRunByAgent: Map<string, { runId: string; liveCount: number }>;
}) {
  const agent = agentMap.get(node.id);

  const statusColor = agentStatusDot[node.status] ?? agentStatusDotDefault;

  return (
    <div style={{ paddingLeft: depth * 24 }}>
      <Link
        to={agent ? agentUrl(agent) : `/agents/${node.id}`}
        className="flex items-center gap-3 px-3 py-2 hover:bg-accent/30 transition-colors w-full text-left no-underline text-inherit"
      >
        <span className="relative flex h-2.5 w-2.5 shrink-0">
          <span className={`absolute inline-flex h-full w-full rounded-full ${statusColor}`} />
        </span>
        <div className="flex-1 min-w-0">
          <span className="text-sm font-medium">{node.name}</span>
          <span className="text-xs text-muted-foreground ml-2">
            {roleLabels[node.role] ?? node.role}
            {agent?.title ? ` - ${agent.title}` : ""}
          </span>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <span className="sm:hidden">
            {liveRunByAgent.has(node.id) ? (
              <LiveRunIndicator
                agentRef={agent ? agentRouteRef(agent) : node.id}
                runId={liveRunByAgent.get(node.id)!.runId}
                liveCount={liveRunByAgent.get(node.id)!.liveCount}
              />
            ) : (
              <StatusBadge status={node.status} />
            )}
          </span>
          <div className="hidden sm:flex items-center gap-3">
            {liveRunByAgent.has(node.id) && (
              <LiveRunIndicator
                agentRef={agent ? agentRouteRef(agent) : node.id}
                runId={liveRunByAgent.get(node.id)!.runId}
                liveCount={liveRunByAgent.get(node.id)!.liveCount}
              />
            )}
            {agent && (
              <>
                <span className="text-xs text-muted-foreground font-mono w-14 text-right">
                  {adapterLabels[agent.adapterType] ?? agent.adapterType}
                </span>
                <span className="text-xs text-muted-foreground w-16 text-right">
                  {agent.lastHeartbeatAt ? relativeTime(agent.lastHeartbeatAt) : "—"}
                </span>
              </>
            )}
            <span className="w-20 flex justify-end">
              <StatusBadge status={node.status} />
            </span>
          </div>
        </div>
      </Link>
      {node.reports && node.reports.length > 0 && (
        <div className="border-l border-border/50 ml-4">
          {node.reports.map((child) => (
            <OrgTreeNode key={child.id} node={child} depth={depth + 1} agentMap={agentMap} liveRunByAgent={liveRunByAgent} />
          ))}
        </div>
      )}
    </div>
  );
}

function LiveRunIndicator({
  agentRef,
  runId,
  liveCount,
}: {
  agentRef: string;
  runId: string;
  liveCount: number;
}) {
  return (
    <Link
      to={`/agents/${agentRef}/runs/${runId}`}
      className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-blue-500/10 hover:bg-blue-500/20 transition-colors no-underline"
      onClick={(e) => e.stopPropagation()}
    >
      <span className="relative flex h-2 w-2">
        <span className="animate-pulse absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75" />
        <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500" />
      </span>
      <span className="text-[11px] font-medium text-blue-600 dark:text-blue-400">
        Live{liveCount > 1 ? ` (${liveCount})` : ""}
      </span>
    </Link>
  );
}

// svelte-ui/src/routes/[companyPrefix]/agents/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { browser } from '$app/environment';
  import { breadcrumbStore } from '$stores/breadcrumb.svelte.js';
  import { companyStore } from '$stores/company.svelte.js';
  import { api } from '$lib/api';
  import { onMount, onDestroy } from 'svelte';
  import { Plus, Bot, List, GitBranch, SlidersHorizontal } from 'lucide-svelte';

  onMount(() => breadcrumbStore.set([{ label: 'Agents' }]));

  // ---------------------------------------------------------------------------
  // Types
  // ---------------------------------------------------------------------------
  interface Agent {
    id: string;
    name: string;
    slug?: string;
    urlKey?: string;
    status: string;
    role: string;
    title?: string | null;
    adapterType: string;
    model?: string | null;
    lastHeartbeatAt?: string | null;
    reportsTo?: string | null;
    createdAt?: string;
    updatedAt?: string;
    [key: string]: unknown;
  }

  interface TreeNode {
    agent: Agent;
    children: TreeNode[];
  }

  type FilterTab = 'all' | 'active' | 'paused' | 'error';

  // ---------------------------------------------------------------------------
  // State
  // ---------------------------------------------------------------------------
  let agents = $state<Agent[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let liveRuns = $state<any[]>([]);
  let activeFilter = $state<FilterTab>('all');
  let showTerminated = $state(false);
  let filtersOpen = $state(false);

  let viewMode = $state<'list' | 'tree'>(
    browser ? (localStorage.getItem('agents-view-mode') as 'list' | 'tree') ?? 'list' : 'list'
  );

  $effect(() => {
    if (browser) localStorage.setItem('agents-view-mode', viewMode);
  });

  let companyId = $derived(companyStore.selectedCompany?.id ?? companyStore.selectedCompanyId);

  // ---------------------------------------------------------------------------
  // Live run map: agentId -> { runId, liveCount }
  // ---------------------------------------------------------------------------
  let liveRunByAgent = $derived.by(() => {
    const map = new Map<string, { runId: string; liveCount: number }>();
    for (const r of liveRuns) {
      if (r.status !== 'running' && r.status !== 'queued') continue;
      const agentId = r.agentId ?? r.agent?.id;
      if (!agentId) continue;
      const existing = map.get(agentId);
      if (existing) { existing.liveCount += 1; continue; }
      map.set(agentId, { runId: r.id, liveCount: 1 });
    }
    return map;
  });

  // ---------------------------------------------------------------------------
  // Filtering
  // ---------------------------------------------------------------------------
  function matchesTab(status: string, tab: FilterTab): boolean {
    if (status === 'terminated') return showTerminated;
    if (tab === 'all') return true;
    if (tab === 'active') return status === 'active' || status === 'running' || status === 'idle';
    if (tab === 'paused') return status === 'paused';
    if (tab === 'error') return status === 'error';
    return true;
  }

  let filteredAgents = $derived.by(() => {
    return agents
      .filter(a => matchesTab(a.status, activeFilter))
      .sort((a, b) => a.name.localeCompare(b.name));
  });

  function countByTab(tab: FilterTab): number {
    const base = showTerminated ? agents : agents.filter(a => a.status !== 'terminated');
    if (tab === 'all') return base.length;
    if (tab === 'active') return base.filter(a => a.status === 'active' || a.status === 'running' || a.status === 'idle').length;
    return base.filter(a => a.status === tab).length;
  }

  // ---------------------------------------------------------------------------
  // Org tree builder
  // ---------------------------------------------------------------------------
  let agentTree = $derived.by(() => {
    const filteredIds = new Set(filteredAgents.map(a => a.id));
    const childrenMap = new Map<string | null, Agent[]>();
    for (const a of filteredAgents) {
      const parentId = a.reportsTo && filteredIds.has(a.reportsTo) ? a.reportsTo : null;
      const list = childrenMap.get(parentId) ?? [];
      list.push(a);
      childrenMap.set(parentId, list);
    }
    function buildNodes(parentId: string | null): TreeNode[] {
      return (childrenMap.get(parentId) ?? []).map(agent => ({
        agent,
        children: buildNodes(agent.id),
      }));
    }
    return buildNodes(null);
  });

  // ---------------------------------------------------------------------------
  // Data fetching
  // ---------------------------------------------------------------------------
  let liveRunsInterval: ReturnType<typeof setInterval> | undefined;

  $effect(() => {
    if (!companyId) return;
    loading = true;
    error = null;
    api(`/api/companies/${companyId}/agents`)
      .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then(d => { agents = (Array.isArray(d) ? d : d.agents ?? []) as Agent[]; })
      .catch(e => { error = e.message ?? 'Failed to load agents'; })
      .finally(() => { loading = false; });
  });

  async function fetchLiveRuns() {
    if (!companyId) return;
    try {
      const res = await api(`/api/companies/${companyId}/live-runs?minCount=0`);
      if (res.ok) {
        const data = await res.json();
        liveRuns = Array.isArray(data) ? data : data.runs ?? data.data ?? [];
      }
    } catch { /* ignore */ }
  }

  onMount(() => {
    fetchLiveRuns();
    liveRunsInterval = setInterval(fetchLiveRuns, 15_000);
  });

  onDestroy(() => {
    if (liveRunsInterval) clearInterval(liveRunsInterval);
  });

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------
  const STATUS_COLORS: Record<string, string> = {
    idle:             'bg-emerald-500',
    active:           'bg-emerald-500',
    running:          'bg-blue-500',
    paused:           'bg-yellow-500',
    error:            'bg-red-500',
    terminated:       'bg-zinc-500',
    pending_approval: 'bg-amber-400',
  };

  function statusDotClass(status: string): string {
    return STATUS_COLORS[status] ?? 'bg-zinc-500';
  }

  const STATUS_BADGE: Record<string, string> = {
    idle:             'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
    active:           'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
    running:          'text-blue-400 bg-blue-500/10 border-blue-500/20',
    paused:           'text-yellow-400 bg-yellow-500/10 border-yellow-500/20',
    error:            'text-red-400 bg-red-500/10 border-red-500/20',
    terminated:       'text-zinc-500 bg-zinc-500/10 border-zinc-500/20',
    pending_approval: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
  };

  function statusBadgeClass(status: string): string {
    return STATUS_BADGE[status] ?? 'text-zinc-500 bg-zinc-500/10 border-zinc-500/20';
  }

  function statusDisplayText(status: string): string {
    const labels: Record<string, string> = {
      idle: 'Idle', active: 'Active', running: 'Running',
      paused: 'Paused', error: 'Error', terminated: 'Terminated',
      pending_approval: 'Pending',
    };
    return labels[status] ?? status;
  }

  function timeAgo(dateStr: string | null | undefined): string {
    if (!dateStr) return '—';
    const diff = Date.now() - new Date(dateStr).getTime();
    const s = Math.floor(diff / 1000);
    if (s < 60) return `${s}s ago`;
    const m = Math.floor(s / 60);
    if (m < 60) return `${m}m ago`;
    const h = Math.floor(m / 60);
    if (h < 24) return `${h}h ago`;
    return `${Math.floor(h / 24)}d ago`;
  }

  const ADAPTER_LABELS: Record<string, string> = {
    claude_local: 'Claude', codex_local: 'Codex', cursor: 'Cursor',
    gemini_local: 'Gemini', pi_local: 'Pi', openclaw_gateway: 'OpenClaw',
    opencode_local: 'OpenCode', process: 'Process', http: 'HTTP',
  };

  const ROLE_LABELS: Record<string, string> = {
    ceo: 'CEO', manager: 'Manager', general: 'General', lead: 'Lead',
  };

  function roleLabel(role: string): string {
    return ROLE_LABELS[role] ?? role;
  }

  const FILTER_TABS: Array<{ value: FilterTab; label: string }> = [
    { value: 'all',    label: 'All'    },
    { value: 'active', label: 'Active' },
    { value: 'paused', label: 'Paused' },
    { value: 'error',  label: 'Error'  },
  ];

  // Close filters dropdown on outside click
  function handleWindowClick(e: MouseEvent) {
    if (filtersOpen && !(e.target as HTMLElement).closest('[data-filters-dropdown]')) {
      filtersOpen = false;
    }
  }
</script>

<svelte:window onclick={handleWindowClick} />

<!-- -------------------------------------------------------------------------
  Snippets
  ------------------------------------------------------------------------- -->

{#snippet agentRowContent(agent: Agent)}
  {@const liveInfo = liveRunByAgent.get(agent.id)}
  {@const subtitle = `${roleLabel(agent.role)}${agent.title ? ` - ${agent.title}` : ''}`}
  {@const agentHref = `/{$page.params.companyPrefix}/agents/{agent.urlKey ?? agent.id}`}
  <div
    role="link"
    tabindex="0"
    onclick={() => goto(agentHref)}
    onkeydown={(e) => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        goto(agentHref);
      }
    }}
    class="flex items-center gap-3 px-3 py-2 hover:bg-accent/30 transition-colors w-full text-left no-underline text-inherit"
  >
    <!-- Status dot -->
    <span class="relative flex h-2.5 w-2.5 shrink-0">
      <span class="absolute inline-flex h-full w-full rounded-full {statusDotClass(agent.status)}"></span>
    </span>

    <!-- Name + subtitle -->
    <div class="flex-1 min-w-0">
      <span class="text-sm font-medium text-foreground">{agent.name}</span>
      <span class="text-xs text-muted-foreground ml-2">{subtitle}</span>
    </div>

    <!-- Trailing -->
    <div class="flex items-center gap-3 shrink-0">
      <!-- Mobile: live indicator or status badge only -->
      <span class="sm:hidden">
        {#if liveInfo}
          <a
            href="/{$page.params.companyPrefix}/runs/{liveInfo.runId}"
            onclick={(e) => e.stopPropagation()}
            class="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-blue-500/10 hover:bg-blue-500/20 transition-colors"
          >
            <span class="relative flex h-2 w-2">
              <span class="animate-pulse absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
              <span class="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
            </span>
            <span class="text-[11px] font-medium text-blue-400">Live{liveInfo.liveCount > 1 ? ` (${liveInfo.liveCount})` : ''}</span>
          </a>
        {:else}
          <span class="inline-flex items-center rounded-full border px-2 py-0.5 text-[11px] font-medium {statusBadgeClass(agent.status)}">
            {statusDisplayText(agent.status)}
          </span>
        {/if}
      </span>

      <!-- Desktop: live indicator + adapter + heartbeat + status -->
      <div class="hidden sm:flex items-center gap-3">
        {#if liveInfo}
          <a
            href="/{$page.params.companyPrefix}/runs/{liveInfo.runId}"
            onclick={(e) => e.stopPropagation()}
            class="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-blue-500/10 hover:bg-blue-500/20 transition-colors"
          >
            <span class="relative flex h-2 w-2">
              <span class="animate-pulse absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
              <span class="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
            </span>
            <span class="text-[11px] font-medium text-blue-400">Live{liveInfo.liveCount > 1 ? ` (${liveInfo.liveCount})` : ''}</span>
          </a>
        {/if}
        <span class="text-xs text-muted-foreground font-mono w-14 text-right">
          {ADAPTER_LABELS[agent.adapterType] ?? agent.adapterType}
        </span>
        <span class="text-xs text-muted-foreground w-16 text-right">
          {timeAgo(agent.lastHeartbeatAt)}
        </span>
        <span class="w-20 flex justify-end">
          <span class="inline-flex items-center rounded-full border px-2 py-0.5 text-[11px] font-medium {statusBadgeClass(agent.status)}">
            {statusDisplayText(agent.status)}
          </span>
        </span>
      </div>
    </div>
  </div>
{/snippet}

{#snippet treeNodes(nodes: TreeNode[], depth: number)}
  {#each nodes as node (node.agent.id)}
    <div style="padding-left: {depth * 24}px">
      {@render agentRowContent(node.agent)}
      {#if node.children.length > 0}
        <div class="border-l border-border/50 ml-4">
          {@render treeNodes(node.children, depth + 1)}
        </div>
      {/if}
    </div>
  {/each}
{/snippet}

<!-- -------------------------------------------------------------------------
  Page
  ------------------------------------------------------------------------- -->

<div class="space-y-4 p-6">
  <!-- Toolbar: tabs + controls -->
  <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
    <!-- Filter tabs -->
    <div class="flex items-center gap-1.5 flex-wrap">
      {#each FILTER_TABS as tab}
        <button
          onclick={() => { activeFilter = tab.value; }}
          class="rounded-lg px-3 py-1.5 text-sm font-medium transition
            {activeFilter === tab.value
              ? 'bg-[#2563EB] text-white'
              : 'bg-accent/60 text-muted-foreground hover:bg-accent hover:text-foreground'}"
        >
          {tab.label}
          <span class="ml-1 text-xs opacity-70">({countByTab(tab.value)})</span>
        </button>
      {/each}
    </div>

    <!-- Controls: Filters + View toggle + New Agent -->
    <div class="flex items-center gap-2">
      <!-- Filters dropdown -->
      <div class="relative" data-filters-dropdown>
        <button
          onclick={() => { filtersOpen = !filtersOpen; }}
          class="flex items-center gap-1.5 px-2 py-1.5 text-xs transition-colors border border-border
            {filtersOpen || showTerminated ? 'text-foreground bg-accent' : 'text-muted-foreground hover:bg-accent/50'}"
        >
          <SlidersHorizontal class="h-3 w-3" />
          Filters
          {#if showTerminated}
            <span class="ml-0.5 px-1 bg-foreground/10 rounded text-[10px]">1</span>
          {/if}
        </button>
        {#if filtersOpen}
          <div class="absolute right-0 top-full mt-1 z-50 w-48 border border-border bg-popover shadow-md p-1">
            <button
              class="flex items-center gap-2 w-full px-2 py-1.5 text-xs text-left hover:bg-accent/50 transition-colors"
              onclick={() => { showTerminated = !showTerminated; }}
            >
              <span
                class="flex items-center justify-center h-3.5 w-3.5 border border-border rounded-sm
                  {showTerminated ? 'bg-foreground' : ''}"
              >
                {#if showTerminated}
                  <span class="text-background text-[10px] leading-none">✓</span>
                {/if}
              </span>
              Show terminated
            </button>
          </div>
        {/if}
      </div>

      <!-- View toggle -->
      <div class="flex items-center border border-border">
        <button
          onclick={() => { viewMode = 'list'; }}
          class="p-1.5 transition-colors {viewMode === 'list' ? 'bg-accent text-foreground' : 'text-muted-foreground hover:bg-accent/50'}"
          title="List view"
        >
          <List class="h-3.5 w-3.5" />
        </button>
        <button
          onclick={() => { viewMode = 'tree'; }}
          class="p-1.5 transition-colors {viewMode === 'tree' ? 'bg-accent text-foreground' : 'text-muted-foreground hover:bg-accent/50'}"
          title="Org tree view"
        >
          <GitBranch class="h-3.5 w-3.5" />
        </button>
      </div>

      <!-- New Agent -->
      <a
        href="/{$page.params.companyPrefix}/agents/new"
        class="inline-flex items-center gap-1.5 rounded border border-border px-3 py-1.5 text-sm font-medium text-foreground transition hover:bg-accent/50"
      >
        <Plus class="h-3.5 w-3.5" />
        New Agent
      </a>
    </div>
  </div>

  <!-- Agent count -->
  {#if !loading && !error && filteredAgents.length > 0}
    <p class="text-xs text-muted-foreground">
      {filteredAgents.length} agent{filteredAgents.length !== 1 ? 's' : ''}
    </p>
  {/if}

  <!-- Loading skeleton -->
  {#if loading}
    <div class="space-y-2">
      {#each Array(6) as _}
        <div class="h-10 animate-pulse rounded bg-card border border-border"></div>
      {/each}
    </div>

  <!-- Error -->
  {:else if error}
    <p class="text-sm text-destructive">{error}</p>

  <!-- No agents at all -->
  {:else if agents.length === 0}
    <div class="flex flex-col items-center justify-center py-16 text-center">
      <div class="rounded-full bg-accent/60 p-4 mb-4">
        <Bot class="w-8 h-8 text-muted-foreground" />
      </div>
      <p class="text-sm text-muted-foreground">Create your first agent to get started.</p>
      <a
        href="/{$page.params.companyPrefix}/agents/new"
        class="mt-3 text-sm text-[#2563EB] hover:underline"
      >
        New Agent
      </a>
    </div>

  <!-- List view -->
  {:else if viewMode === 'list'}
    {#if filteredAgents.length > 0}
      <div class="border border-border">
        {#each filteredAgents as agent (agent.id)}
          {@render agentRowContent(agent)}
        {/each}
      </div>
    {:else}
      <p class="text-sm text-muted-foreground text-center py-8">No agents match the selected filter.</p>
    {/if}

  <!-- Org tree view -->
  {:else}
    {#if agentTree.length > 0}
      <div class="border border-border py-1">
        {@render treeNodes(agentTree, 0)}
      </div>
    {:else}
      <p class="text-sm text-muted-foreground text-center py-8">No organizational hierarchy defined.</p>
    {/if}
  {/if}
</div>
